blank_issues_enabled: false
contact_links:
  - name: 🌐 Vurro Website
    url: https://vurro.net
    about: Learn more about the Vurro extension.
  - name: 🛒 Chrome Web Store
    url: https://chromewebstore.google.com/detail/iiikcncocbihjgghlcmdbimdnkjbemdc
    about: Install or review Vurro on the Chrome Web Store.
  - name: 🦊 Firefox Add-ons
    url: https://addons.mozilla.org/en-US/firefox/addon/vurro-for-substack/
    about: Install or review Vurro on Firefox Add-ons.
